# Generated by Django 4.2.1 on 2023-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maxPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='rangePrice',
            field=models.BooleanField(default=False),
        ),
    ]
