# Generated by Django 4.2.1 on 2023-06-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_caracteristiques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
