# Generated by Django 4.2.1 on 2023-06-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configomatic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refroidissement',
            name='consommation',
        ),
    ]
